spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.113.223.247:3306/clean
    username: root
    password: fxg666

# 配置SpringBoot的启动端口 即服务器会占用本机8081端口
server:
  port: 8081